### ISSUE TITLE
wish: Changelog

### ISSUE THREAD

**Issue by markstos** [OverZealous/run-sequence#82] opened 2016-10-25 21:06 UTC
It would be helpful to have a human-friendly log of what's changed between versions. http://keepachangelog.com

**Comment by OverZealous** [comment] 2016-10-25 21:08
I suppose, though I've only really made one breaking change so far.  And this project is pretty well static at this point.

**Comment by markstos** [comment] 2016-10-25 21:34
In my case, I'm running roughly 1.0 and was trying to figure out if upgrading to the latest version would fix the issue I was having. The Changelog would have been helpful. In this case it didn't take long to just test the new release by trying it out.

**Comment by nicolasalejandrorodriguez** [comment] 2017-06-30 20:46
Hello! With the new version of chalk we have problem building our project

![image](https://user-images.githubusercontent.com/24395363/27753377-c13f18a8-5dbb-11e7-8320-f966d1b27f46.png)

![image](https://user-images.githubusercontent.com/24395363/27753447-04b36e72-5dbc-11e7-950d-3ebc36e5eeb4.png)

**Comment by OverZealous** [comment] 2017-06-30 20:49
@nicolasalejandrorodriguez This was discussed in #90 and #89 and fixed in v2.0.0

Also, please don't comment on existing bugs with unrelated issues.

**Comment by nicolasalejandrorodriguez** [comment] 2017-06-30 20:57
Thanks, and sorry. I will delete my comment to not spam the issue

**Comment by OverZealous** [comment] 2017-06-30 20:58
No problem, you don't have to delete your comment. Just make a new issue in the future. Thanks!

**Comment by jwhitmarsh** [comment] 2017-07-07 09:35
Since this is open - why was the major version changed? Do we need to watch out for any breaking changes?

**Comment by OverZealous** [comment] 2017-07-07 15:21
The library didn't specify a version for dependencies, leading to unexpected behavior as Chalk dropped support for old versions of Node. To prevent unexpected behavior, I released the update with specific version dependencies as a new major release.
For more details, please see #89

**Comment by markstos** [comment] 2017-07-10 14:59
Releasing 2.0 would have been a great time to add the Changelog requested in this issue and could save further support time being spent to answer questions in the issue tracker about "why the major version bump?" since the answer is not easily found in a Changelog as expected.

**Comment by OverZealous** [comment] 2017-07-10 15:01
I get that, it just wasn't a prioity since I was trying to get a fix out for people with broken builds, and was sick all last week.

**Closed** 2017-07-10 15:37 UTC
Labels: enhancement
