### ISSUE TITLE
Empty task list should not throw Error

### ISSUE THREAD

**Issue by atirip** [OverZealous/run-sequence#46] opened 2015-08-12 12:11 UTC
In case task list is built dynamically, it may happen (and happened to me) that the list will be empty. In such case there is no reason to throw an Error, better would be just call callback and continue silently. Maybe a warning.

**Comment by OverZealous** [comment] 2015-08-12 12:48
Duplicate of #43.  The library works as intended.

**Closed by OverZealous** 2015-08-12 12:48 UTC
Labels: invalid, wontfix
