### ISSUE TITLE
Abort sequence when jshint fails

### ISSUE THREAD

**Issue by katowulf** [OverZealous/run-sequence#20] opened 2015-01-15 16:48 UTC
Hi there!  Jshint provides a fail reporter to fail the task when errors exists. However, this doesn't seem to work from within run-sequence.

```
var seq = require('run-sequence');
var jshint = require('gulp-jshint');

gulp.task('lint', function() {
   return gulp.src(['./src/**/*.js'])
      .pipe(jshint())
      .pipe(jshint.reporter('jshint-stylish'))
      .pipe(jshint.reporter('fail'));    
});

gulp.task('build', function() {
    return /* build process */;
});

gulp.task('bundle', function() {
    return seq('lint', 'build');  // build runs event if the 'lint' task fails : (
});
```

**Comment by katowulf** [comment] 2015-01-15 16:52
This could also be an issue with gulp-jshint. Can you help me isolate the failure point? I'm happy to PR if I can understand the problem.

**Comment by OverZealous** [comment] 2015-01-16 02:42
run-sequence should stop a sequence if the task fails correctly: https://github.com/OverZealous/run-sequence/blob/master/index.js#L83

**Comment by OverZealous** [comment] 2015-01-22 22:22
@katowulf Have you resolved this issue yet?

**Comment by OverZealous** [comment] 2015-01-29 23:04
Closing as I am unable to reproduce without further information.

@katowulf If you continue to have issues, I'll happily reopen this bug.

**Closed by OverZealous** 2015-01-29 23:04 UTC
