### ISSUE TITLE
nested runSequences

### ISSUE THREAD

**Issue by geofflancaster** [OverZealous/run-sequence#19] opened 2015-01-06 22:49 UTC
Is it possible to have a runSequence call a task that executes another runSequence? I'm having issues where the script is exiting before the tasks are complete.

**Comment by OverZealous** [comment] 2015-01-07 01:19
First, if your script is exiting before tasks are complete, you are most likely [**not** setting up your async tasks correctly](https://github.com/gulpjs/gulp/blob/master/docs/API.md#async-task-support).  Please read over the gulp documentation to make sure you have every task configured correctly.

Beyond that, I can't tell you for sure if running nested calls will work or not.  I *think*, as long as you don't try to run the same task (by task name) in any of the nested calls, it should work.  run-sequence simply listens for the `task_stop` event from Orchestrator, then checks off it's list of internal tasks as they are completed, and starts the next sequential task if there are any more.

**Comment by OverZealous** [comment] 2015-01-22 22:22
@geofflancaster Have you looked into this any more? I haven't heard back from you in a while.

**Comment by OverZealous** [comment] 2015-01-29 23:03
Closing as I am unable to reproduce.

**Closed by OverZealous** 2015-01-29 23:03 UTC
